[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin=lib/openzeppelin-contracts"]

# Number of runs in a fuzz test
[fuzz]
runs = 1000

[invariant]
runs = 128
depth = 128
fail_on_revert = false
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
